/**
 * SVG element parser — extracts individual elements from SVG markup strings.
 * Used by adapter.ts to create element-level document nodes instead of
 * monolithic legacy:* svg-fragment nodes.
 *
 * Parsing is intentionally regex-based (not DOM-based) because:
 * 1. The artwork SVG is generated by the engine, not user-authored HTML.
 * 2. We need to run in both browser and Node (vitest) without DOM dependencies.
 * 3. We only need to identify top-level <text>, <rect>, <circle>, <path>,
 *    <image>, <line>, <ellipse>, <polygon>, <g> elements with their attributes.
 */

import type { DesignNode, DocumentNodeRole, NodeBounds } from './types'
import { identityTransform } from './types'

export type ParsedElement = {
  tag: string
  attrs: Record<string, string>
  /** Inner text content for <text> elements. */
  text?: string
  /** Raw outer markup. */
  markup: string
}

const SELF_CLOSING_TAGS = new Set(['rect', 'circle', 'ellipse', 'line', 'path', 'image', 'polygon', 'polyline'])

/** Parse top-level SVG elements from a markup string. */
export function parseSvgElements(markup: string): ParsedElement[] {
  const elements: ParsedElement[] = []
  // Match opening tag + attributes, then either self-close or find closing tag
  const tagRe = /<(text|rect|circle|ellipse|line|path|image|polygon|polyline|g)\b([^>]*?)(\/?)>/g
  let match: RegExpExecArray | null
  while ((match = tagRe.exec(markup)) !== null) {
    const tag = match[1]
    const attrStr = match[2]
    const selfClose = match[3] === '/'
    const tagStart = match.index
    const tagEnd = tagStart + match[0].length
    const attrs = parseAttrs(attrStr)

    if (SELF_CLOSING_TAGS.has(tag) || selfClose) {
      elements.push({
        tag,
        attrs,
        markup: markup.slice(tagStart, tagEnd),
      })
      continue
    }

    // Non-self-closing: find matching closing tag
    const closeTag = `</${tag}>`
    const closeIdx = markup.indexOf(closeTag, tagEnd)
    if (closeIdx === -1) {
      // Malformed — skip
      continue
    }
    const fullEnd = closeIdx + closeTag.length
    const inner = markup.slice(tagEnd, closeIdx)
    elements.push({
      tag,
      attrs,
      text: tag === 'text' ? inner.replace(/<[^>]+>/g, '').trim() : undefined,
      markup: markup.slice(tagStart, fullEnd),
    })
    tagRe.lastIndex = fullEnd
  }
  return elements
}

function parseAttrs(attrStr: string): Record<string, string> {
  const attrs: Record<string, string> = {}
  const attrRe = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*"([^"]*)"/g
  let m: RegExpExecArray | null
  while ((m = attrRe.exec(attrStr)) !== null) {
    attrs[m[1]] = m[2]
  }
  return attrs
}

/** Extract numeric value from an attribute string. */
function num(attrs: Record<string, string>, key: string, fallback = 0): number {
  const v = parseFloat(attrs[key] ?? '')
  return Number.isFinite(v) ? v : fallback
}

/** Infer bounds from element attributes. */
export function elementBounds(el: ParsedElement): NodeBounds {
  const { tag, attrs } = el
  if (tag === 'rect') {
    const x = num(attrs, 'x')
    const y = num(attrs, 'y')
    return { x, y, w: num(attrs, 'width'), h: num(attrs, 'height') }
  }
  if (tag === 'circle') {
    const cx = num(attrs, 'cx')
    const cy = num(attrs, 'cy')
    const r = num(attrs, 'r')
    return { x: cx - r, y: cy - r, w: r * 2, h: r * 2 }
  }
  if (tag === 'ellipse') {
    const cx = num(attrs, 'cx')
    const cy = num(attrs, 'cy')
    const rx = num(attrs, 'rx')
    const ry = num(attrs, 'ry')
    return { x: cx - rx, y: cy - ry, w: rx * 2, h: ry * 2 }
  }
  if (tag === 'image') {
    const x = num(attrs, 'x')
    const y = num(attrs, 'y')
    return { x, y, w: num(attrs, 'width'), h: num(attrs, 'height') }
  }
  if (tag === 'line') {
    const x1 = num(attrs, 'x1')
    const y1 = num(attrs, 'y1')
    const x2 = num(attrs, 'x2')
    const y2 = num(attrs, 'y2')
    return { x: Math.min(x1, x2), y: Math.min(y1, y2), w: Math.abs(x2 - x1), h: Math.abs(y2 - y1) }
  }
  if (tag === 'polygon' || tag === 'polyline') {
    const pts = (attrs.points ?? '').split(/\s+/).map(Number).filter(Number.isFinite)
    if (pts.length < 4) return { x: 0, y: 0, w: 0, h: 0 }
    const xs: number[] = []
    const ys: number[] = []
    for (let i = 0; i + 1 < pts.length; i += 2) {
      xs.push(pts[i])
      ys.push(pts[i + 1])
    }
    const minX = Math.min(...xs)
    const maxX = Math.max(...xs)
    const minY = Math.min(...ys)
    const maxY = Math.max(...ys)
    return { x: minX, y: minY, w: maxX - minX, h: maxY - minY }
  }
  if (tag === 'text') {
    const x = num(attrs, 'x')
    const y = num(attrs, 'y')
    const fontSize = num(attrs, 'font-size', 3)
    return { x, y: y - fontSize, w: 40, h: fontSize * 1.4 }
  }
  // path or group — no reliable bounds without full path parsing
  return { x: 0, y: 0, w: 0, h: 0 }
}

/** Infer document role from element tag + attributes. */
export function elementRole(el: ParsedElement): DocumentNodeRole {
  const { tag, attrs } = el
  if (tag === 'text') {
    const cls = attrs['data-art'] ?? ''
    if (/brand|lockup/i.test(cls)) return 'brand'
    if (/product|title/i.test(cls)) return 'product'
    return 'copy'
  }
  if (tag === 'image') return 'image' as DocumentNodeRole
  if (tag === 'path' || tag === 'rect' || tag === 'circle' || tag === 'ellipse' || tag === 'polygon' || tag === 'line') {
    const cls = attrs['data-art'] ?? ''
    if (/hero/i.test(cls)) return 'hero'
    if (/bg|background/i.test(cls)) return 'background'
    if (/decor|frame|pattern/i.test(cls)) return 'decor'
    if (/mark|seal|barcode/i.test(cls)) return 'mark'
    return 'decor'
  }
  if (tag === 'g') {
    const cls = attrs['data-art'] ?? attrs['data-hero'] ?? ''
    if (/hero/i.test(cls)) return 'hero'
    if (/bg|background/i.test(cls)) return 'background'
    if (/decor|frame|pattern/i.test(cls)) return 'decor'
    if (/mark|seal/i.test(cls)) return 'mark'
    return 'decor'
  }
  return 'decor'
}

/** Convert a parsed element to a DesignNode. */
export function elementToNode(
  el: ParsedElement,
  id: string,
  panelId: string,
  zIndex: number,
): DesignNode | null {
  const bounds = elementBounds(el)
  const role = elementRole(el)
  const base = {
    id,
    panelId,
    name: `${el.tag} ${id}`,
    role,
    bounds,
    transform: identityTransform(),
    visible: true,
    locked: true,
    zIndex,
  }

  if (el.tag === 'text') {
    const fontSize = num(el.attrs, 'font-size', 3)
    return {
      ...base,
      kind: 'text' as const,
      text: el.text ?? '',
      style: {
        fill: el.attrs.fill ?? '#000',
        fontFamily: el.attrs['font-family'] ?? 'Inter, Arial, sans-serif',
        fontSizeMm: fontSize,
        fontWeight: parseInt(el.attrs['font-weight'] ?? '400', 10),
        letterSpacingMm: num(el.attrs, 'letter-spacing'),
        textAnchor: (el.attrs['text-anchor'] ?? 'start') as 'start' | 'middle' | 'end',
      },
    }
  }

  if (el.tag === 'image') {
    return {
      ...base,
      kind: 'image' as const,
      href: el.attrs.href ?? '',
      preserveAspectRatio: (el.attrs['preserveAspectRatio']?.includes('slice') ? 'slice' : el.attrs['preserveAspectRatio'] === 'none' ? 'none' : 'meet') as 'meet' | 'slice' | 'none',
      opacity: num(el.attrs, 'opacity', 1),
    }
  }

  if (el.tag === 'path') {
    return {
      ...base,
      kind: 'shape' as const,
      path: el.attrs.d ?? '',
      style: {
        fill: el.attrs.fill ?? 'none',
        stroke: el.attrs.stroke ?? 'none',
        strokeWidthMm: num(el.attrs, 'stroke-width'),
        opacity: num(el.attrs, 'opacity', 1),
      },
    }
  }

  // rect, circle, ellipse, line, polygon, g → svg-fragment
  return {
    ...base,
    kind: 'svg-fragment' as const,
    markup: el.markup,
  }
}
