/**
 * Export-time text outlining.
 *
 * A downloaded print file must render identically on a machine that has none of the studio
 * fonts installed. Declaring `@font-face { src: local(...) }` does not achieve that — the
 * renderer silently falls back and every fitted line shifts. Illustrator, the tool a printer
 * is most likely to open the SVG in, also ignores fonts embedded in SVG.
 *
 * So the exporter converts every glyph to a path. The studio canvas is untouched: editing still
 * happens on the live model, and outlining is applied only to the artifact that leaves the app.
 *
 * Glyph data comes from `fontOutlines.json`, generated by `scripts/build-font-outlines.py` from
 * the vendored SIL OFL subsets. It is imported dynamically so it never enters the main bundle.
 */

type Glyph = [advance: number, path: string]
type OutlineTable = { em: number; faces: Record<string, Record<string, Glyph>> }

let tablePromise: Promise<OutlineTable> | null = null

async function loadTable(): Promise<OutlineTable> {
  if (!tablePromise) {
    tablePromise = import('./fontOutlines.json').then((m) => (m.default ?? m) as unknown as OutlineTable)
  }
  return tablePromise
}

/** Markup carries family + weight + style; map that back to a generated face key. */
export function resolveFaceKey(family: string, weight: number, italic: boolean): string {
  const fam = family.toLowerCase()
  if (/great vibes|allura|brush script|cursive/.test(fam)) return 'greatvibes-400'
  // Phase 4 faces — each stack leads with its own family, so the test is on the first name.
  if (/instrument serif/.test(fam)) return italic ? 'instrumentserif-400i' : 'instrumentserif-400'
  if (/barlow condensed|oswald|arial narrow/.test(fam)) return weight >= 700 ? 'barlowcondensed-700' : 'barlowcondensed-600'
  if (/righteous|fredoka|rounded/.test(fam)) return 'righteous-400'
  if (/plex mono|jetbrains mono|consolas|courier|monospace/.test(fam)) return weight >= 500 ? 'ibmplexmono-500' : 'ibmplexmono-400'
  // Order matters: a Montserrat stack ends in "sans-serif", which contains "serif".
  const sans = /montserrat|inter|segoe|arial|helvetica|sans/.test(fam)
  if (!sans && /cormorant|playfair|garamond|georgia|times|serif/.test(fam)) {
    if (italic) return 'cormorant-500i'
    if (weight >= 700) return 'cormorant-700'
    if (weight >= 600) return 'cormorant-600'
    return 'cormorant-500'
  }
  // Everything else is a sans — including the Inter numerals drawn inside mark glyphs.
  if (weight >= 700) return 'montserrat-700'
  if (weight <= 300) return 'montserrat-300'
  return 'montserrat-500'
}

function attr(tag: string, name: string): string | undefined {
  const m = tag.match(new RegExp(`\\s${name}="([^"]*)"`))
  return m?.[1]
}

function unescapeSvg(s: string): string {
  return s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&')
}

/** Strips nested markup (tspan) so the run is laid out as one string. */
function plainText(inner: string): string {
  return unescapeSvg(inner.replace(/<[^>]*>/g, ''))
}

export type OutlineReport = { total: number; outlined: number; missing: string[]; glyphs: number }

/**
 * How many glyphs were drawn. This used to be a pool of shared `<path id>` definitions that `<use>`
 * referenced — smaller, and unreadable in Illustrator (see the note where the glyph is written).
 * The count survives because the report is asserted on; the sharing does not.
 */
class GlyphPool {
  private drawn = 0

  count(): void {
    this.drawn += 1
  }

  get size(): number {
    return this.drawn
  }

  markup(): string {
    return ''
  }
}

function outlineOne(tag: string, inner: string, table: OutlineTable, report: OutlineReport, pool: GlyphPool): string {
  const text = plainText(inner)
  if (!text.trim()) return ''

  const size = Number(attr(tag, 'font-size') ?? 0)
  const x = Number(attr(tag, 'x') ?? 0)
  const y = Number(attr(tag, 'y') ?? 0)
  if (!Number.isFinite(size) || size <= 0) return `<text${tag}>${inner}</text>`

  const family = attr(tag, 'font-family') ?? ''
  const weight = Number(attr(tag, 'font-weight') ?? 400) || 400
  const italic = /italic/.test(attr(tag, 'font-style') ?? '')
  const faceKey = resolveFaceKey(family, weight, italic)
  const face = table.faces[faceKey]
  if (!face) {
    report.missing.push(faceKey)
    return `<text${tag}>${inner}</text>`
  }

  const em = table.em
  const scale = size / em
  const trackingMm = Number(attr(tag, 'letter-spacing') ?? 0) || 0
  const trackingUnits = trackingMm / scale

  // Lay out in font units first so the anchor shift is exact.
  const chars = [...text]
  let width = 0
  for (const ch of chars) {
    const g = face[ch] ?? face[' ']
    width += (g?.[0] ?? em * 0.5) + trackingUnits
  }
  if (chars.length) width -= trackingUnits

  const anchor = attr(tag, 'text-anchor') ?? 'start'
  const shift = anchor === 'middle' ? -width / 2 : anchor === 'end' ? -width : 0

  let cursor = shift
  let body = ''
  for (const ch of chars) {
    const g = face[ch]
    if (g) {
      if (g[1]) {
        /*
         * The glyph is written out, not referenced.
         *
         * This used to emit `<use href="#g12" x="…"/>` against a pool of `<path id>` definitions,
         * which is smaller and correct SVG 2 — and invisible in Illustrator. Illustrator's importer
         * is SVG 1.1, where the attribute is `xlink:href` and the namespace has to be declared;
         * given a bare `href` it resolves nothing and draws nothing. The owner opened a delivered
         * file and found the design there but the type missing, which is exactly that.
         *
         * Adding `xlink:href` would probably work. Inlining cannot fail: no ids, no namespace, no
         * cross-references, nothing for an importer to resolve. A print file is opened once by a
         * printer, so the extra kilobytes buy the one property that matters.
         */
        pool.count()
        body += `<path transform="translate(${cursor.toFixed(1)} 0)" d="${g[1]}"/>`
      }
      cursor += g[0] + trackingUnits
    } else {
      report.missing.push(ch)
      cursor += (face[' ']?.[0] ?? em * 0.5) + trackingUnits
    }
  }
  report.outlined += 1

  const fill = attr(tag, 'fill') ?? '#000'
  const opacity = attr(tag, 'opacity')
  const transform = attr(tag, 'transform')
  // y flips because font outlines are y-up and SVG user space is y-down.
  const place = `translate(${x} ${y}) scale(${scale.toFixed(6)} ${(-scale).toFixed(6)})`
  const outer = transform ? `${transform} ${place}` : place
  return `<g transform="${outer}" fill="${fill}"${opacity ? ` opacity="${opacity}"` : ''} data-art="outlined-text">${body}</g>`
}

/**
 * Replaces every `<text>` run in the markup with vector paths.
 * Returns the markup unchanged for runs whose face is unavailable, so export never loses copy.
 */
export async function outlineSvgText(markup: string): Promise<{ markup: string; report: OutlineReport }> {
  const table = await loadTable()
  const report: OutlineReport = { total: 0, outlined: 0, missing: [], glyphs: 0 }
  const pool = new GlyphPool()
  const body = markup.replace(/<text([^>]*)>([\s\S]*?)<\/text>/g, (_full, tag: string, inner: string) => {
    report.total += 1
    return outlineOne(tag, inner, table, report, pool)
  })
  report.glyphs = pool.size
  // Once every run is a path the font declarations are dead weight — and worse, they imply a
  // dependency that no longer exists. Drop them only when nothing was left as live text.
  const cleaned =
    report.total > 0 && report.outlined === report.total
      ? body.replace(/<style data-art="studio-fonts(?:-subset)?">[\s\S]*?<\/style>/g, '')
      : body
  const defs = pool.markup()
  if (!defs) return { markup: cleaned, report }
  // Defs must live inside the root <svg>; put them right after the opening tag.
  const open = cleaned.match(/<svg[^>]*>/)
  const out = open ? cleaned.replace(open[0], `${open[0]}${defs}`) : `${defs}${cleaned}`
  return { markup: out, report }
}
