/**
 * Studio gallery set — 9 sectors × box + label.
 * Shared by the Desktop export script and the S6 golden hash test.
 * Catalog/freeze jobs stay in scripts/catalog-jobs.ts.
 */
import type { PackagingMode, StyleType } from '../../types'

export type StudioGalleryJob = {
  slug: string
  brand: string
  product: string
  sector: string
  subProduct: string
  packagingMode: PackagingMode
  templateId: string
  styleType: StyleType
  colors: string
  volume: string
  dimensionsMm: { L: number; W: number; H: number }
}

export const STUDIO_GALLERY_JOBS: StudioGalleryJob[] = [
  {
    slug: '01-parfum-kutu',
    brand: 'REBULL NOIR',
    product: 'Sauvage',
    sector: 'parfüm',
    subProduct: 'eau de parfum',
    packagingMode: 'box',
    templateId: 'fm-cos-tuck-perfume',
    styleType: 'luxury',
    colors: '#0b0b0b #c9a45c',
    volume: '100 ml',
    dimensionsMm: { L: 70, W: 35, H: 140 },
  },
  {
    slug: '01-parfum-etiket',
    brand: 'REBULL NOIR',
    product: 'Sauvage',
    sector: 'parfüm',
    subProduct: 'eau de parfum',
    packagingMode: 'label',
    templateId: 'fm-cos-label-bottle',
    styleType: 'luxury',
    colors: '#f3ead8 #1a2744',
    volume: '100 ml',
    dimensionsMm: { L: 90, W: 0, H: 140 },
  },
  {
    slug: '02-krem-kutu',
    brand: 'woo.originals',
    product: 'Care Cream',
    sector: 'kozmetik',
    subProduct: 'krem',
    packagingMode: 'box',
    templateId: 'fm-cos-tuck-cream',
    styleType: 'playful',
    colors: '#2bb7b3 #ffffff',
    volume: '250 ml',
    dimensionsMm: { L: 80, W: 40, H: 80 },
  },
  {
    slug: '02-krem-etiket',
    brand: 'woo.originals',
    product: 'Restorative Shampoo',
    sector: 'kozmetik',
    subProduct: 'şampuan',
    packagingMode: 'label',
    templateId: 'fm-label-universal',
    styleType: 'playful',
    colors: '#8fd14f #1a3d12',
    volume: '500 ml',
    dimensionsMm: { L: 110, W: 0, H: 90 },
  },
  {
    slug: '03-serum-kutu',
    brand: 'LUMA',
    product: 'Glow Serum',
    sector: 'kozmetik',
    subProduct: 'serum',
    packagingMode: 'box',
    templateId: 'fm-cos-tuck-serum',
    styleType: 'minimal',
    colors: '#f7f4ee #2d6a4f',
    volume: '30 ml',
    dimensionsMm: { L: 45, W: 45, H: 120 },
  },
  {
    slug: '03-serum-etiket',
    brand: 'LUMA',
    product: 'Glow Serum',
    sector: 'kozmetik',
    subProduct: 'serum',
    packagingMode: 'label',
    templateId: 'fm-cos-label-bottle',
    styleType: 'minimal',
    colors: '#eef6f2 #1f4d3a',
    volume: '30 ml',
    dimensionsMm: { L: 70, W: 0, H: 55 },
  },
  {
    slug: '04-gida-bal-kutu',
    brand: 'ANADOLU BAL',
    product: 'Dağ Çiçeği',
    sector: 'gıda',
    subProduct: 'bal',
    packagingMode: 'box',
    templateId: 'fm-food-tuck-oil',
    styleType: 'classic',
    colors: '#f3e9d3 #b8892f',
    volume: '450 g',
    dimensionsMm: { L: 85, W: 55, H: 110 },
  },
  {
    slug: '04-gida-bal-etiket',
    brand: 'ANADOLU BAL',
    product: 'Dağ Çiçeği',
    sector: 'gıda',
    subProduct: 'bal',
    packagingMode: 'label',
    templateId: 'fm-food-label-jar',
    styleType: 'eco',
    colors: '#efe4c8 #5a3a12',
    volume: '450 g',
    dimensionsMm: { L: 80, W: 0, H: 100 },
  },
  {
    slug: '05-kahve-kutu',
    brand: 'ELITE BREW',
    product: 'Mocha Frappe',
    sector: 'gıda',
    subProduct: 'kahve',
    packagingMode: 'box',
    templateId: 'fm-box-sleeve',
    styleType: 'luxury',
    colors: '#1b2a4a #c9a45c',
    volume: '250 g',
    dimensionsMm: { L: 80, W: 50, H: 180 },
  },
  {
    slug: '05-kahve-etiket',
    brand: 'ELITE BREW',
    product: 'Cold Brew',
    sector: 'gıda',
    subProduct: 'kahve',
    packagingMode: 'label',
    templateId: 'fm-label-universal',
    styleType: 'luxury',
    colors: '#f4dcc8 #1b2a4a',
    volume: '250 ml',
    dimensionsMm: { L: 70, W: 0, H: 120 },
  },
  {
    slug: '06-elektronik-kutu',
    brand: 'NOX',
    product: 'Pulse Buds',
    sector: 'elektronik',
    subProduct: 'kulaklık',
    packagingMode: 'box',
    templateId: 'fm-elec-tuck-earbuds',
    styleType: 'modern',
    colors: '#15181d #6fd3e0',
    volume: '1 adet',
    dimensionsMm: { L: 90, W: 90, H: 45 },
  },
  {
    slug: '06-elektronik-etiket',
    brand: 'NOX',
    product: 'Pulse Buds',
    sector: 'elektronik',
    subProduct: 'kulaklık',
    packagingMode: 'label',
    templateId: 'fm-elec-label-device',
    styleType: 'modern',
    colors: '#0e1116 #8ab4ff',
    volume: '1 adet',
    dimensionsMm: { L: 120, W: 0, H: 50 },
  },
  {
    slug: '07-bebek-kutu',
    brand: 'MİA',
    product: 'Soft Care',
    sector: 'bebek',
    subProduct: 'bakım',
    packagingMode: 'box',
    templateId: 'fm-box-tuck-universal',
    styleType: 'playful',
    colors: '#f7e8d0 #3d7a5a',
    volume: '200 ml',
    dimensionsMm: { L: 75, W: 40, H: 95 },
  },
  {
    slug: '07-bebek-etiket',
    brand: 'MİA',
    product: 'Soft Care',
    sector: 'bebek',
    subProduct: 'bakım',
    packagingMode: 'label',
    templateId: 'fm-label-universal',
    styleType: 'playful',
    colors: '#fff6ea #2f6b4e',
    volume: '200 ml',
    dimensionsMm: { L: 95, W: 0, H: 70 },
  },
  {
    slug: '08-saglik-kutu',
    brand: 'DNA PHARMA',
    product: 'Sea Protection',
    sector: 'sağlık',
    subProduct: 'takviye',
    packagingMode: 'box',
    templateId: 'fm-box-reverse-tuck',
    styleType: 'minimal',
    colors: '#ffffff #f2a93b',
    volume: '60 kapsül',
    dimensionsMm: { L: 70, W: 40, H: 110 },
  },
  {
    slug: '08-saglik-etiket',
    brand: 'DNA PHARMA',
    product: 'Sea Protection',
    sector: 'sağlık',
    subProduct: 'takviye',
    packagingMode: 'label',
    templateId: 'fm-label-universal',
    styleType: 'minimal',
    colors: '#f8fafc #1e3a5f',
    volume: '60 kapsül',
    dimensionsMm: { L: 85, W: 0, H: 85 },
  },
  {
    slug: '09-temizlik-kutu',
    brand: 'FERAH',
    product: 'Konsantre',
    sector: 'temizlik',
    subProduct: 'deterjan',
    packagingMode: 'box',
    templateId: 'fm-box-snap-lock',
    styleType: 'eco',
    colors: '#e8f4ea #1f6b4a',
    volume: '1 L',
    dimensionsMm: { L: 90, W: 50, H: 160 },
  },
  {
    slug: '09-temizlik-etiket',
    brand: 'FERAH',
    product: 'Konsantre',
    sector: 'temizlik',
    subProduct: 'deterjan',
    packagingMode: 'label',
    templateId: 'fm-label-universal',
    styleType: 'eco',
    colors: '#d9efe0 #14523b',
    volume: '1 L',
    dimensionsMm: { L: 100, W: 0, H: 75 },
  },
]
