import type { DesignBrief, PackagingMode, StyleType } from '../src/types'
import type { HeroFamily } from '../src/engine/brain/DesignPlan'

export type Job = {
  slug: string
  sectorFolder: string
  title: string
  brandName: string
  productName: string
  sector: string
  subProduct: string
  templateId: string
  packagingMode: PackagingMode
  styleType: StyleType
  colors: string
  volume: string
  heroFamily?: HeroFamily
  variationIndex?: number
}

export const JOBS: Job[] = [
  {
    slug: '01-parfum-tuck-luxury',
    sectorFolder: '01-parfum',
    title: 'Parfüm tuck-end',
    brandName: 'AURELIA',
    productName: 'Noir',
    sector: 'parfüm',
    subProduct: 'eau de parfum',
    templateId: 'fm-cos-tuck-perfume',
    packagingMode: 'box',
    styleType: 'luxury',
    colors: 'siyah altın',
    volume: '50 ml',
  },
  {
    slug: '02-kolonya-tuck-classic',
    sectorFolder: '01-parfum',
    title: 'Kolonya tuck-end',
    brandName: 'LUCENT',
    productName: 'Aqua',
    sector: 'parfüm',
    subProduct: 'kolonya',
    templateId: 'fm-cos-tuck-perfume',
    packagingMode: 'box',
    styleType: 'classic',
    colors: 'lacivert gümüş',
    volume: '100 ml',
  },
  {
    slug: '03-krem-tuck-luxury',
    sectorFolder: '02-krem',
    title: 'Krem kutusu',
    brandName: 'LUMINA',
    productName: 'Night Cream',
    sector: 'kozmetik',
    subProduct: 'krem',
    templateId: 'fm-cos-tuck-cream',
    packagingMode: 'box',
    styleType: 'luxury',
    colors: 'krem nude',
    volume: '50 ml',
  },
  {
    slug: '04-serum-tuck-minimal',
    sectorFolder: '03-serum',
    title: 'Serum kutusu',
    brandName: 'CLARA',
    productName: 'Concentrate',
    sector: 'kozmetik',
    subProduct: 'serum',
    templateId: 'fm-cos-tuck-serum',
    packagingMode: 'box',
    styleType: 'minimal',
    colors: 'beyaz',
    volume: '30 ml',
  },
  {
    slug: '05-parfum-wrap-luxury',
    sectorFolder: '01-parfum',
    title: 'Parfüm wrap etiket',
    brandName: 'AURELIA',
    productName: 'Noir',
    sector: 'parfüm',
    subProduct: 'parfüm',
    templateId: 'fm-cos-label-bottle',
    packagingMode: 'label',
    styleType: 'luxury',
    colors: 'siyah altın',
    volume: '50 ml',
  },
  {
    slug: '06-krem-wrap-modern',
    sectorFolder: '02-krem',
    title: 'Krem wrap etiket',
    brandName: 'LUMINA',
    productName: 'Night Cream',
    sector: 'kozmetik',
    subProduct: 'krem',
    templateId: 'fm-cos-label-bottle',
    packagingMode: 'label',
    styleType: 'modern',
    colors: 'krem nude',
    volume: '50 ml',
  },
  {
    slug: '07-serum-wrap-minimal',
    sectorFolder: '03-serum',
    title: 'Serum wrap etiket',
    brandName: 'CLARA',
    productName: 'Concentrate',
    sector: 'kozmetik',
    subProduct: 'serum',
    templateId: 'fm-cos-label-bottle',
    packagingMode: 'label',
    styleType: 'minimal',
    colors: 'beyaz',
    volume: '30 ml',
  },
  {
    slug: '08-zeytinyagi-tuck-luxury',
    sectorFolder: '04-gida',
    title: 'Yağ / sos kutusu',
    brandName: 'TERRA GROVE',
    productName: 'Sızma',
    sector: 'gıda',
    subProduct: 'zeytinyağı',
    templateId: 'fm-food-tuck-oil',
    packagingMode: 'box',
    styleType: 'luxury',
    colors: 'zeytin altın',
    volume: '500 ml',
  },
  {
    slug: '09-cikolata-tray-playful',
    sectorFolder: '04-gida',
    title: 'Atıştırmalık tepsisi',
    brandName: 'NIB',
    productName: 'Cacao',
    sector: 'gıda',
    subProduct: 'çikolata',
    templateId: 'fm-food-tray-snack',
    packagingMode: 'box',
    styleType: 'playful',
    colors: 'terracotta',
    volume: '80 g',
  },
  {
    slug: '10-kurabiye-tray-classic',
    sectorFolder: '04-gida',
    title: 'Kurabiye tepsisi',
    brandName: 'MILL',
    productName: 'Biscuit',
    sector: 'gıda',
    subProduct: 'kurabiye',
    templateId: 'fm-food-tray-snack',
    packagingMode: 'box',
    styleType: 'classic',
    colors: 'krem kahve',
    volume: '180 g',
  },
  {
    slug: '11-bal-label-classic',
    sectorFolder: '04-gida',
    title: 'Bal kavanoz etiketi',
    brandName: 'YAYLA',
    productName: 'Çiçek Balı',
    sector: 'gıda',
    subProduct: 'bal',
    templateId: 'fm-food-label-jar',
    packagingMode: 'label',
    styleType: 'classic',
    colors: 'altın krem',
    volume: '340 g',
  },
  {
    slug: '12-recel-label-eco',
    sectorFolder: '04-gida',
    title: 'Reçel kavanoz etiketi',
    brandName: 'BAHÇE',
    productName: 'Vişne',
    sector: 'gıda',
    subProduct: 'reçel',
    templateId: 'fm-food-label-jar',
    packagingMode: 'label',
    styleType: 'eco',
    colors: 'bordo',
    volume: '300 g',
  },
  {
    slug: '13-cay-label-eco',
    sectorFolder: '04-gida',
    title: 'Çay kavanoz etiketi',
    brandName: 'DAĞ',
    productName: 'Adaçayı',
    sector: 'gıda',
    subProduct: 'çay',
    templateId: 'fm-food-label-jar',
    packagingMode: 'label',
    styleType: 'eco',
    colors: 'yeşil',
    volume: '100 g',
  },
  {
    slug: '14-kulaklik-tuck-modern',
    sectorFolder: '05-elektronik',
    title: 'Kulaklık kutusu',
    brandName: 'NOX',
    productName: 'Pulse',
    sector: 'elektronik',
    subProduct: 'kulaklık',
    templateId: 'fm-elec-tuck-earbuds',
    packagingMode: 'box',
    styleType: 'modern',
    colors: 'siyah',
    volume: '1 adet',
  },
  {
    slug: '15-kablo-tuck-modern',
    sectorFolder: '05-elektronik',
    title: 'Aksesuar kutusu',
    brandName: 'NOX',
    productName: 'Charge',
    sector: 'elektronik',
    subProduct: 'kablo',
    templateId: 'fm-elec-tuck-cable',
    packagingMode: 'box',
    styleType: 'modern',
    colors: 'siyah gümüş',
    volume: '1 m',
  },
  {
    slug: '16-cihaz-label-minimal',
    sectorFolder: '05-elektronik',
    title: 'Cihaz düz etiket',
    brandName: 'NOX',
    productName: 'Module',
    sector: 'elektronik',
    subProduct: 'cihaz',
    templateId: 'fm-elec-label-device',
    packagingMode: 'label',
    styleType: 'minimal',
    colors: 'siyah',
    volume: '',
  },
  {
    slug: '17-evrensel-kozmetik-tuck',
    sectorFolder: '06-evrensel',
    title: 'Evrensel tuck — kozmetik',
    brandName: 'FORMA',
    productName: 'Studio',
    sector: 'kozmetik',
    subProduct: 'genel',
    templateId: 'fm-box-tuck-universal',
    packagingMode: 'box',
    styleType: 'luxury',
    colors: 'siyah altın',
    volume: '50 ml',
  },
  {
    slug: '18-evrensel-gida-tuck',
    sectorFolder: '06-evrensel',
    title: 'Evrensel tuck — gıda',
    brandName: 'FORMA',
    productName: 'Pantry',
    sector: 'gıda',
    subProduct: 'genel',
    templateId: 'fm-box-tuck-universal',
    packagingMode: 'box',
    styleType: 'classic',
    colors: 'krem zeytin',
    volume: '250 g',
  },
  {
    slug: '19-evrensel-elektronik-tuck',
    sectorFolder: '06-evrensel',
    title: 'Evrensel tuck — elektronik',
    brandName: 'FORMA',
    productName: 'Tech',
    sector: 'elektronik',
    subProduct: 'genel',
    templateId: 'fm-box-tuck-universal',
    packagingMode: 'box',
    styleType: 'modern',
    colors: 'siyah',
    volume: '1 adet',
  },
  {
    slug: '20-temizlik-tuck-minimal',
    sectorFolder: '07-temizlik',
    title: 'Temizlik — evrensel tuck',
    brandName: 'PURE',
    productName: 'Surface',
    sector: 'temizlik',
    subProduct: 'yüzey bakım',
    templateId: 'fm-box-tuck-universal',
    packagingMode: 'box',
    styleType: 'minimal',
    colors: 'beyaz',
    volume: '750 ml',
  },
  {
    slug: '21-krem-eco-monstera',
    sectorFolder: '08-hero-library',
    title: 'Krem eco — monstera',
    brandName: 'LUMINA',
    productName: 'Leaf',
    sector: 'kozmetik',
    subProduct: 'krem',
    templateId: 'fm-cos-tuck-cream',
    packagingMode: 'box',
    styleType: 'eco',
    colors: 'yeşil krem',
    volume: '50 ml',
    heroFamily: 'monstera',
    variationIndex: 1,
  },
  {
    slug: '22-serum-eco-monstera',
    sectorFolder: '08-hero-library',
    title: 'Serum eco — monstera',
    brandName: 'CLARA',
    productName: 'Verdant',
    sector: 'kozmetik',
    subProduct: 'serum',
    templateId: 'fm-cos-tuck-serum',
    packagingMode: 'box',
    styleType: 'eco',
    colors: 'yeşil',
    volume: '30 ml',
    heroFamily: 'monstera',
    variationIndex: 1,
  },
  {
    slug: '23-krem-eco-palm',
    sectorFolder: '08-hero-library',
    title: 'Krem eco — palm',
    brandName: 'LUMINA',
    productName: 'Palme',
    sector: 'kozmetik',
    subProduct: 'krem',
    templateId: 'fm-cos-label-bottle',
    packagingMode: 'label',
    styleType: 'eco',
    colors: 'yeşil krem',
    volume: '50 ml',
    heroFamily: 'palm',
    variationIndex: 2,
  },
  {
    slug: '24-krem-playful-palm',
    sectorFolder: '08-hero-library',
    title: 'Krem playful — palm',
    brandName: 'LUMINA',
    productName: 'Tropic',
    sector: 'kozmetik',
    subProduct: 'krem',
    templateId: 'fm-cos-tuck-cream',
    packagingMode: 'box',
    styleType: 'playful',
    colors: 'pembe',
    volume: '50 ml',
    heroFamily: 'palm',
    variationIndex: 3,
  },
  {
    slug: '25-krem-playful-wave',
    sectorFolder: '08-hero-library',
    title: 'Krem playful — organic-wave',
    brandName: 'LUMINA',
    productName: 'Bloom',
    sector: 'kozmetik',
    subProduct: 'krem',
    templateId: 'fm-cos-tuck-cream',
    packagingMode: 'box',
    styleType: 'playful',
    colors: 'pembe',
    volume: '50 ml',
    heroFamily: 'organic-wave',
    variationIndex: 1,
  },
  {
    slug: '26-serum-playful-wave',
    sectorFolder: '08-hero-library',
    title: 'Serum playful — organic-wave',
    brandName: 'CLARA',
    productName: 'Pulse',
    sector: 'kozmetik',
    subProduct: 'serum',
    templateId: 'fm-cos-label-bottle',
    packagingMode: 'label',
    styleType: 'playful',
    colors: 'pembe',
    volume: '30 ml',
    heroFamily: 'organic-wave',
    variationIndex: 2,
  },
  {
    slug: '27-krem-modern-zebra',
    sectorFolder: '08-hero-library',
    title: 'Krem modern — zebra',
    brandName: 'LUMINA',
    productName: 'Stripe',
    sector: 'kozmetik',
    subProduct: 'krem',
    templateId: 'fm-cos-tuck-cream',
    packagingMode: 'box',
    styleType: 'modern',
    colors: 'siyah',
    volume: '50 ml',
    heroFamily: 'zebra',
    variationIndex: 1,
  },
  {
    slug: '28-serum-modern-zebra',
    sectorFolder: '08-hero-library',
    title: 'Serum modern — zebra',
    brandName: 'CLARA',
    productName: 'Graphic',
    sector: 'kozmetik',
    subProduct: 'serum',
    templateId: 'fm-cos-tuck-serum',
    packagingMode: 'box',
    styleType: 'modern',
    colors: 'siyah',
    volume: '30 ml',
    heroFamily: 'zebra',
    variationIndex: 4,
  },
]

export function briefFrom(job: Job): DesignBrief {
  return {
    brandName: job.brandName,
    productName: job.productName,
    sector: job.sector,
    subProduct: job.subProduct,
    packagingMode: job.packagingMode,
    templateId: job.templateId,
    dimensionsMm: { L: 0, W: 0, H: 0 },
    styleType: job.styleType,
    colors: job.colors,
    volume: job.volume,
    barcode: '',
    manufacturerName: `${job.brandName} Üretim A.Ş.`,
    manufacturerAddress: 'Örnek Mah. No:1, 34000 İstanbul, TR',
    logo: '',
    references: '',
    copyOverrides: '',
  }
}

